### ISSUE TITLE
using TextEditingController in FlutterSummernote

### ISSUE THREAD

**Issue by blue492** [chandrabezzo/flutter_summernote#1]
Hi,
Is there any way to save the String value directly from the TextField into a controller (TextEditingController) without using keyEditor.currentState.getText()

I need to use a controller because sometimes I got null value when I used this:
final txt = await keyEditor.currentState.getText();

It will be good if you add a controller like this:

```
FlutterSummernote(
                controller: comment_control,
                hint: "Your text here...",
                //value: "text content initial, if any",
                key: keyEditor,
              ),
```

Thanks for good library

**Comment by afandiyusuf** [comment]
Sorry, I can't resolve this bug for further troubleshooting, since I always get what I expected with getText().

@blue492 can you give any example code that make keyEditor.currentState.getText() that resulting null?
Please add flutter doctor -v and what version do you use for this library.

Feel free to reopen this issue

**Comment by blue492** [comment]
The problem appear if use in FlutterSummernote in ListView which have many widgets, that means the list will be long and sometimes you need to scroll down or up in the list. If you have  FlutterSummernote at the top of the list and you write something it will show the text you wrote, but when you scroll down at the bottom of ListView and Scroll up again to FlutterSummernote you will see that the text you wrote has been removed. 

I think the problem is that FlutterSummernote widget rebuild itself when you scroll down or up, that is why the text will be removed. _keyEditor should always save the text and FlutterSummernote should not rebuild itself when I scroll down or up. 

When I put the the save button at the ListView bottom it return null to me when I call: 
`final txt = await keyEditor.currentState.getText();`

In this case, I need either to add FlutterSummernote with save button in  AlertDialog or in a sperate page to get data.

I hope that you understood me @afandiyusuf 
Thanks
