### ISSUE TITLE
Support for null safety

### ISSUE THREAD

**Issue by manjotsidhu** [chandrabezzo/flutter_summernote#28]
This is a request to add support for [null safety](https://dart.dev/null-safety) .
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See this [blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide)  for details about enabling null safety.

**Comment by JEuler** [comment]
Please close the issue, if the answer was helpful. :)

**Comment by manjotsidhu** [comment]
@chandrabezzo can we see this null safety published to pub.dev ?

**Comment by chandrabezzo** [comment]
Hi @manjotsidhu sorry for being late, I was published null safety to pub.dev as `flutter_summernote: ^1.0.0`, Thank you.
